### ISSUE TITLE
обсуждение дз

### ISSUE THREAD

**Issue by Andreystudent** [MIEE-ACS/domashnee-zadanie-no4-Andreystudent#1]
Дмитрий Владимирович, мне кажется , что одно из условий второй задачи ( а именно по поиску номера столбца с самой длинной серией одинаковых жлементов) не совсем корректно сформулировано .
Как следствие, у меня получился не очень убедительный  способ поиска этого столбца.

**Comment by d-makarenko** [comment]
А почему ты думаешь, что некорректно?
На самом деле, хотя задания поставлены очень абстрактно, они могут решать вполне жизненные задачи. Например, у нас есть некоторая выборка данных, допустим телеметрия с датчиков, где каждый столбец содержит данные с отдельного датчика. И нам нужно узнать с какого из датчика приходят наиболее стабильные (не изменяющиеся во времени) данные. Вот это как раз твой вариант.

**Comment by d-makarenko** [comment]
У тебя решение правильное.
